# Generated by Django 5.0.4 on 2024-04-11 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='ward',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Patient_History',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('hname', models.CharField(max_length=255)),
                ('pimage', models.ImageField(upload_to='images')),
                ('file', models.FileField(upload_to='files')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctors')),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
